### ISSUE TITLE
Wake after...

### ISSUE THREAD

**Issue by zz0rk** [Deminder/ShutdownTimer#2]
**Describe the bug**
Wake only succeeds to wake from suspend when "Toggle wake with shutdown timer" is enabled, otherwise system remains suspended. When woken from suspend in above manner the shutdown/restart prompt is set to shutdown the system within 60 seconds.
- If applicable, show log appropriate output `journalctl /usr/bin/gnome-shell -o cat`
N/A
- Does the bug only occur in with an additional gnome shell extension enabled or with only the "Shutdown Timer" extension enabled ?
No

**To Reproduce**
Extension Settings > Wake and set "Toggle wake with shutdown timer" to enabled 
Shutdown Timer menu
Select Suspend in 1 minute
Select Wake after 3 minutes
System will suspend and wake but is set to shutdown within 60 seconds.

**Expected behavior**
System should wake from suspend and remain in unsuspended state.

**Screenshots**

**System specifications (please complete the following information):**
 - Extension version: current
 - GNOME shell version `gnome-shell --version`: GNOME Shell 3.36.9
 - Ubuntu 18.04, Fedora 31, Manjaro 19.02, Arch, Debian 10.3, openSUSE Leap 15.1, etc.: Ubuntu 20.04 LTS

![image](https://user-images.githubusercontent.com/18619265/129655008-040f6fa9-4fe7-4268-ac47-fd0accb9d182.png)

**Comment by Deminder** [comment]
The bug was a missing break statement here:
https://github.com/Deminder/ShutdownTimer/blob/ab912a1e9cbeb8297ba014f8e8dddc7db7ff3b59/extension.js#L238-L239
This should be fixed with the release 14:
https://github.com/Deminder/ShutdownTimer/blob/d9649a774c695de35edfece2ea148575eee18ccd/extension.js#L231-L233

Thanks for testing the extension and your bug report :+1:
