### ISSUE TITLE
Extension Fails to Turn Off Automatically After Waking System from Suspension

### ISSUE THREAD

**Issue by nullstreak** [Deminder/ShutdownTimer#21]
**Describe the bug**
The Shutdown Timer extension does not turn off automatically after waking the system up from suspension. Instead, the timer continues to display "now" indefinitely until it is manually turned off by the user. The bug occurs with only the Shutdown Timer extension enabled.

**To Reproduce**
1. Enable the Shutdown Timer extension.
2. Set a timer for a specific duration (e.g. 1 minute).
3. Set use mode to "Suspend" and activate the timer.
4. Wait for timer to run out and suspend the system.
5. Wake the system up from suspension.
6. Observe that the timer does not turn off automatically and continues to display "now" indefinitely.

**Expected behavior**
The Shutdown Timer extension should automatically turn off after the PC is woken up from suspension. The timer should not continue to display "now" indefinitely.

**System**
- Extension version: 36
- GNOME shell version: GNOME Shell 43.9
- Distro: Debian GNU/Linux 12 (bookworm)

**Comment by Deminder** [comment]
@nullstreak Thank you for this bug report!

I think, this happens since the extension is not periodically checking whether the timer has expired, anymore.

I found another bug which, as far I can see, is part of the same problem:
1. Set a timer for a specific duration (e.g. 1 minute).
2. `systemctl suspend` and wait 2 minutes
3.  Wake system
4. Observe that  after 1 minute the system suspends again.

The problem should be fixed by periodically checking whether the timer has expired and discarding overdue timers.

**Comment by nullstreak** [comment]
@Deminder I believe there is a third bug. Sometimes after waking up from suspend, my system completely freezes showing the lock screen. Everything is frozen including the keyboard, only a complete reboot helps. I had this happen twice only when using this extension.

**Comment by Deminder** [comment]
> @Deminder I believe there is a third bug. Sometimes after waking up from suspend, my system completely freezes showing the lock screen. Everything is frozen including the keyboard, only a complete reboot helps. I had this happen twice only when using this extension.

This is weird, maybe this is not a problem anymore after this bug is fixed. Otherwise, log output (e.g. `journalctl /usr/bin/gnome-shell`) would be helpful to investigate this, since this sounds like the gnome-shell crashing.
