### ISSUE TITLE
No shutdown scheduled.

### ISSUE THREAD

**Issue by bartoszek** [Deminder/ShutdownTimer#23]
**Describe the bug**
Shutdown is not getting scheduled.

**To Reproduce**
[Screencast from 2024-04-29 10-36-57.webm](https://github.com/Deminder/ShutdownTimer/assets/1213348/818c50eb-d419-457d-95c9-2468a8bae21a)

**System**
- Extension version: 43
- GNOME shell version: 46.1
- Distro: Arch

**Comment by Deminder** [comment]
1. The root/system shutdown (which can be seen via  `shutdown --show`) is only used if you enable `Settings > Shutdown > Toggle root shutdown with shutdown timer`. (It is disabled by default)

2. However, I am not able to reproduce no shutdown action being run (with  `Shutdown Timer stopped`). It should show a poweroff dialog.
 
In order to see what is happening on your system, debug logging would be helpful. To enable debug logging set `export const debugMode = true;` in `~/.local/share/gnome-shell/extensions/ShutdownTimer\@deminder/modules/util.js` then restart gnome-shell (by logout and login).
